apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: backend          # arbitrary label on deployment
spec:
  replicas: 4
  selector:
    matchLabels:        # labels the replica selector should match
      app: backend
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: backend      # label for replica selector to match
    spec:
      containers:
      - name: backend
        image: nicolaj2903/devops-cookie-nsn-backend:latest
        env:
          - name: REDIS_DNS
            value: redis
      #  ports:
       # - containerPort: 9000