apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: frontend          # arbitrary label on deployment
spec:
  replicas: 4
  selector:
    matchLabels:        # labels the replica selector should match
      app: frontend
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: frontend      # label for replica selector to match
    spec:
      containers:
      - name: frontend
        image: nicolaj2903/devops-cookie-nsn-frontend
        env:
        - name: BACKEND_DNS
          value: backend
        - name: BACKEND_PORT
          value: "9000"  
    #    ports:
    #    - containerPort: 8080