name: deploy
on:
  push:
    branches:
      - main
jobs:
  deployment:
    name: "Deploy to Kubernetes"
    runs-on: [self-hosted]
    steps:
      - name: Deploy to kubernetes
        run: /home/ubuntu/simple-fortune-cookie/setup.sh
