name: contiuous-integration
on: push
jobs:
  build-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Clone-down
        uses: actions/checkout@v2
      - name: Install dependencies
        run: cd backend && go get github.com/gomodule/redigo/redis
      - name: Build backend
        run: cd backend && go build
  build-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Clone-down
        uses: actions/checkout@v2
      - name: Build frontend
        run: cd frontend && go build
      - name: Upload build artifact
        uses: actions/upload-artifact@v2
  frontend-tests:
    runs-on: ubuntu-latest
    needs: ['build-frontend']   
    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v2 
      - name: Test frontend
        run: cd frontend && go test
      
